# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BuglyProOverSeaDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'BuglyProOverSea', :podspec=>'https://raw.githubusercontent.com/BuglyDevTeam/BuglyProOverSea-iOS/main/BuglyProOverSea.podspec'

  # Pods for BuglyProOverSeaDemo

  target 'BuglyProOverSeaDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuglyProOverSeaDemoUITests' do
    # Pods for testing
  end

end
